hook.Add("DrG/ToolMenu", "DrGHUD/ToolMenu", function(AddCategory)
  AddCategory("drghud.menu", function(AddSubCategory)
    AddSubCategory("server", nil, function(panel, GetText)
      --
    end)

    AddSubCategory("client", nil, function(panel, GetText)
      panel:ControlHelp("\n"..GetText("colors"))
      panel:Button(GetText("colors.reset"), "drghud_cmd_reset_colors")
      DrGHUD.MainColor:AddToPanel(panel, GetText("colors.main"))
      DrGHUD.FullHealthColor:AddToPanel(panel, GetText("colors.full_health"))
      DrGHUD.LowHealthColor:AddToPanel(panel, GetText("colors.low_health"))
      DrGHUD.ArmorColor:AddToPanel(panel, GetText("colors.armor"))
      DrGHUD.AmmoColor:AddToPanel(panel, GetText("colors.ammo"))
      DrGHUD.Ammo2Color:AddToPanel(panel, GetText("colors.ammo2"))
      DrGHUD.NeutralColor:AddToPanel(panel, GetText("colors.neutral"))
      DrGHUD.AllyColor:AddToPanel(panel, GetText("colors.ally"))
      DrGHUD.EnemyColor:AddToPanel(panel, GetText("colors.enemy"))
      DrGHUD.VehicleColor:AddToPanel(panel, GetText("colors.vehicle"))
      DrGHUD.WeaponColor:AddToPanel(panel, GetText("colors.weapon"))
    end)
  end)
end)