hook.Add("DrG/LoadLanguages", "DrGHUD/EnglishLanguage", function()
  local lang = DrGBase.GetOrCreateLanguage("en")

  lang:Set("drghud.status.health", "Health")
  lang:Set("drghud.status.armor", "Armor")
  lang:Set("drghud.entity_info.health", "Health")
  lang:Set("drghud.compass.north", "N")
  lang:Set("drghud.compass.south", "S")
  lang:Set("drghud.compass.east", "E")
  lang:Set("drghud.compass.west", "W")

  lang:Set("drghud.menu", "HUD")
  lang:Set("drghud.menu.server", "Server Settings")
  lang:Set("drghud.menu.client", "Client Settings")
  lang:Set("drghud.menu.client.colors", "Colors")
  lang:Set("drghud.menu.client.colors.reset", "Default colors")
  lang:Set("drghud.menu.client.colors.main", "Main color")
  lang:Set("drghud.menu.client.colors.full_health", "Full health")
  lang:Set("drghud.menu.client.colors.low_health", "Low health")
  lang:Set("drghud.menu.client.colors.armor", "Armor")
  lang:Set("drghud.menu.client.colors.ammo", "Primary ammo")
  lang:Set("drghud.menu.client.colors.ammo2", "Secondary ammo")
  lang:Set("drghud.menu.client.colors.neutral", "Neutral")
  lang:Set("drghud.menu.client.colors.ally", "Allies")
  lang:Set("drghud.menu.client.colors.enemy", "Enemies")
  lang:Set("drghud.menu.client.colors.vehicle", "Vehicles")
  lang:Set("drghud.menu.client.colors.weapon", "Weapons")
end)