hook.Add("DrG/LoadLanguages", "DrGHUD/FrenchLanguage", function()
  local lang = DrGBase.GetOrCreateLanguage("fr")

  lang:Set("drghud.status.health", "Santé")
  lang:Set("drghud.status.armor", "Armure")
  lang:Set("drghud.entity_info.health", "Santé")
  lang:Set("drghud.compass.north", "N")
  lang:Set("drghud.compass.south", "S")
  lang:Set("drghud.compass.east", "E")
  lang:Set("drghud.compass.west", "O")

  lang:Set("drghud.menu", "HUD")
  lang:Set("drghud.menu.server", "Paramètres serveur")
  lang:Set("drghud.menu.client", "Paramètres client")
  lang:Set("drghud.menu.client.colors", "Couleurs")
  lang:Set("drghud.menu.client.colors.reset", "Couleurs par défaut")
  lang:Set("drghud.menu.client.colors.main", "Couleur principale")
  lang:Set("drghud.menu.client.colors.full_health", "Santé pleine")
  lang:Set("drghud.menu.client.colors.low_health", "Santé faible")
  lang:Set("drghud.menu.client.colors.armor", "Armure")
  lang:Set("drghud.menu.client.colors.ammo", "Munitions principales")
  lang:Set("drghud.menu.client.colors.ammo2", "Munitions secondaires")
  lang:Set("drghud.menu.client.colors.neutral", "Neutre")
  lang:Set("drghud.menu.client.colors.ally", "Alliés")
  lang:Set("drghud.menu.client.colors.enemy", "Ennemis")
  lang:Set("drghud.menu.client.colors.vehicle", "Véhicules")
  lang:Set("drghud.menu.client.colors.weapon", "Armes")
end)